### ISSUE TITLE
Do you have any experimental results at resolutions higher than 320x320?

### ISSUE THREAD

**Issue by Jeonghoon4** [janghyuncho/PiCIE#1]
Thanks for the interesting research.

Do you have any experimental results at resolutions higher than 320x320?
Does a higher resolution improve the detail of an object?

**Comment by janghyuncho** [comment]
Thanks for your interest in our project! 

I have not tested training PiCIE with image resolutions larger than 320x320 (this is already increased compared to the benchmark from prior works), but increasing image resolution only during inference still does improve the details of objects. Optionally, you can apply post-process such as CRF, which improves the  details quite a lot. I will upload the weights and the jupyter notebook that you can play with.

**Comment by Jeonghoon4** [comment]
When the ImageNet feature is visualized using CAM, it shows very rough details. So I think your method based on the ImageNet feature will also show similar results.

I'm going to try your comments.

Thanks for the answer.
