### ISSUE TITLE
The PiCIE pre-trained weights are not usable

### ISSUE THREAD

**Issue by vali19th** [janghyuncho/PiCIE#11]
When I try to untar the archive using `tar -xvf picie_coco.tar `, I get this error:
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

I have also tried to extract with archive manager, without a terminal

**Comment by janghyuncho** [comment]
Hi vali19th, 

You can just load it as it is. (e.g., use 'torch.load("picie_coco.tar")')

**Comment by vali19th** [comment]
It worked! Thanks for the quick response.
