### ISSUE TITLE
AttributeError: module 'modules.fpn' has no attribute 'FPN'

### ISSUE THREAD

**Issue by cychss6305** [janghyuncho/PiCIE#12]
Hi @janghyuncho . Thanks for the great research.

When I want to try the visualize.ipynb. I got this error about fpn.
![picle](https://user-images.githubusercontent.com/29619039/136503502-aec5c701-4b3a-4ccd-930a-b2e73ba890c5.PNG)

Can you fix it?
Thanks.

**Comment by yreenabbas** [comment]
Hi @janghyuncho 
Can you fix it ,pleas 
Time is running

**Comment by janghyuncho** [comment]
Hi, 

Can you please try with the updated code? 

Thank you!
