### ISSUE TITLE
NameError: name 'get_args' is not defined

### ISSUE THREAD

**Issue by aipkk** [janghyuncho/PiCIE#14]
Hello @janghyuncho ! 

Your research is amazing, great job :)

I have been working with it, but when I run: 

python prepare_histogram.py --data_root datasets --save_root results --stuff --thing

I get the following error:

C: \...\PiCIE\prepare_histogram.py", line 51, in <module>
    args = get_args()
NameError: name 'get_args' is not defined

Am I missing something or should I change something in the prepare_hsitogram.py? 
I am guessing that function is not called, but I can't figure out where is located, so I can add it, any ideas?

Thanks for your time!

**Comment by janghyuncho** [comment]
Hi aipkk, 

My apologies, I think the jupyter notebook and the histogram code is outdated. I will fix it this week. 

Sorry for the delay !

**Comment by janghyuncho** [comment]
Hi aipkk,

My apologies for the huge delay, I have been very busy with a deadline ... 

I fixed "prepare_histogram.py" and uploaded the necessary files to help visualization easier.

Thank you!
