### ISSUE TITLE
Request of Cityscapes models

### ISSUE THREAD

**Issue by LeungTsang** [janghyuncho/PiCIE#17]
Hi, 

Thank you for your inspiring work. I am also working on self-supervised approaches for semantic segmentation. I hope to have a fair comparison with your work on Cityscapes. However, I could not find enough information to reproduce the best results in the paper and this repo. Could you provide your models trained on Cityscapes? I'd highly appreciate some help.

**Comment by janghyuncho** [comment]
Hi LeungTsang,

Thank you for your interest in our work and consideration to compare our method, and sorry for the delayed answer. 

[Here](https://urldefense.com/v3/__https://drive.google.com/file/d/1phk0hlpFT2RMmOqzQ6Csoj6HgnZFskbK/view?usp=sharing__;!!OToaGQ!4f5kMMLjSy4HWv9ov9Th7sF3SGJ4ZfvKkeQjRLpqnPPoZxGh7Hu5Lcqhg6F-awOuR4lG$) is the pre-trained PiCIE on Cityscapes. 

I am currently very busy with the deadline, but I will push training and testing code for Cityscapes.

Thank you!

**Comment by LeungTsang** [comment]
Thank you! Wish your next work can achieve more.

**Comment by janghyuncho** [comment]
Hi, I uploaded the training end evaluation code for cityscapes for [picie](https://github.com/janghyuncho/PiCIE/blob/master/train_picie.py) and [mdc](https://github.com/janghyuncho/PiCIE/blob/master/train_mdc.py) ([log](https://github.com/janghyuncho/PiCIE/tree/master/logs/reproduce)). 

Sorry for the delay. 

Thank you!
