### ISSUE TITLE
IIC and Deep Cluster models

### ISSUE THREAD

**Issue by vobecant** [janghyuncho/PiCIE#18]
Dear @janghyuncho ,

thank you very much for your work. Would it please be possible to also shared the other baselines (IIC, modified DC) trained on Cityscapes? It would be of a great help.

Thank you very much in advance.

**Comment by janghyuncho** [comment]
Hi vobecant,

Thank you for your interest in PiCIE. I uploaded MDC models for both COCO and Cityscapes, but the IIC models are trained from the official code base and it will take more time to include it in this repo.
