### ISSUE TITLE
Coco validation set annotations

### ISSUE THREAD

**Issue by QingyongHu** [janghyuncho/PiCIE#2]
Thanks for your great work!

How can I get the validation annotations [here](https://github.com/janghyuncho/PiCIE/blob/c8a1438b351c0747e8e24ad59067cbc8d0b3f0ed/data/coco_eval_dataset.py#L65)?

Thanks,

**Comment by janghyuncho** [comment]
Thank you for your interest in our work!

You can download the annotations from the official website [here](http://images.cocodataset.org/annotations/annotations_trainval2017.zip). Then, please refer to the README to set the file structure correctly.

**Comment by QingyongHu** [comment]
Hi, @janghyuncho
Thanks for your reply! Yes, I have followed the instruction and download the dataset and annotations. However, it seems that there is no png file [here](https://github.com/janghyuncho/PiCIE/blob/c8a1438b351c0747e8e24ad59067cbc8d0b3f0ed/data/coco_eval_dataset.py#L65)?

Thanks

**Comment by QingyongHu** [comment]
Hi @janghyuncho, I have found it, here is the annotation [link](http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/stuffthingmaps_trainval2017.zip).

Many thanks!

**Comment by janghyuncho** [comment]
Thank you! I will update the README :)
