### ISSUE TITLE
Error in `prepare_histogram.py`

### ISSUE THREAD

**Issue by TNA8** [janghyuncho/PiCIE#21]
Thanks for sharing such great work.
I was gonna try to run `visualize.ipynb`. To do that, I run
```
python prepare_histogram.py --data_root datasets --save_root results --stuff --thing
```

But I faced this error
![screenshot_70](https://user-images.githubusercontent.com/58914448/144205547-506bb9a6-73b1-427d-aaf0-c2130e58ab59.png)

Could you help me?

And if I want to get labels(masks) for unlabeled images, what should I run?

Thanks in advance.

**Comment by janghyuncho** [comment]
Hi TNA8,

Thank you for your interest in our work! The visualization code is updated and it should work now.
