### ISSUE TITLE
The higher the acc indicator, the smaller the miou

### ISSUE THREAD

**Issue by wuleibegreat** [janghyuncho/PiCIE#22]
Thank you very much for such a meaningful work, but I have a question here that I want to ask. In the process of training the cityscapes dataset,the higher the acc indicator, the smaller the miou.Have you ever encountered this situation?

**Comment by janghyuncho** [comment]
Hello @wuleibegreat,

Thank you for your interest in PiCIE! 

I have not seen a huge degrading pattern on PiCIE, but for MDC and IIC I did see that early in the epoch they have high mIoU. I assume that mIoU is class-balanced metric and some methods tend to overfit to a certain type of categories. 

You can find the training log for PiCIE on both datasets [here](https://github.com/janghyuncho/PiCIE/tree/master/logs/reproduce).  

Hope this answers your question!
