### ISSUE TITLE
About dataset setting

### ISSUE THREAD

**Issue by cychss6305** [janghyuncho/PiCIE#23]
Hi @janghyuncho . Thanks for the great research.
For only stuff or only thing , I wanna know the dataset setting which in your comparison of the performance in Table 2 or Table 4 in your paper.
Is your setting the same with IIC?, like if want to train for only stuff , and the number of stuff catergory is 15,
so set the K is 15, and mask the those objects belong to thing in all the images in datasets?
Thanks.

**Comment by janghyuncho** [comment]
Hi @cychss6305, 

Thank you for your interest in PiCIE! 

For Table 2, we only evaluated the models from Table 1 and evaluated only on Stuff/Things/All categories, by setting the other classes "ignored". This is consistent with the setting in Table 4. We followed the exact setting from IIC paper for Table 4. 

Hope this answers your question.
