### ISSUE TITLE
Visualization for training set.

### ISSUE THREAD

**Issue by easm002** [janghyuncho/PiCIE#24]
Hi Jang,

Thank you for your great work.

I was running the code on my own unlabeled dataset.

Is there a way to obtain segmentation maps of my training dataset?

**Comment by janghyuncho** [comment]
Hi easm002,

Thank you for your interest in our work and sorry for the delay in response. 

You can simply train PiCIE pretrained either on public datasets or your own, and evaluate using evaluation code. 

Best, 
Jang Hyun
