### ISSUE TITLE
comparsion between U-net and FPN

### ISSUE THREAD

**Issue by zhangzihui247** [janghyuncho/PiCIE#25]
Hello, 

Thanks for this great work. I have a question about the network in this paper. I saw that  you use FPN which is, I think, very similar with U-net. So, why you choose FPN? I think U-net is used more frequent in segmentation.

Thanks,
zihui

**Comment by janghyuncho** [comment]
Hello zhangzihui247,

Thank you for your interest in PiCIE! And sorry for the delay in response. 

The FPN was a simplest choice to incorporate hierarchical features into each (pixel-level) feature. U-net can also be used, but it will effectively increase the number of datapoints in clustering step too large. There can be many tricks to avoid such memory issue as different types of sampling, but we did not explore such directions. 

Thank you,
Jang Hyun
