### ISSUE TITLE
How to do the same geometric transformation before and after FPN(input)?

### ISSUE THREAD

**Issue by JudgeLJX** [janghyuncho/PiCIE#27]
Hi, thanks for your code.
I have an issue, in the training processing, we need to do the same transformation for the two input:
        input1 = eqv_transform_if_needed(args, dataloader, indice, input1.cuda(non_blocking=True))
        featmap1 = model(input1)
        
        input2 = input2.cuda(non_blocking=True)
        featmap2 = eqv_transform_if_needed(args, dataloader, indice, model(input2))

however, when the input2 image is passed from the FPN model, it generates different dimensional output compared to the input1, how to make sure that these two transformations have the same effects?

**Comment by janghyuncho** [comment]
Hi JudgeLJX,

Thank you for your interest in our work! 

We pass the same geometric transformation for the two input. [Here](https://github.com/janghyuncho/PiCIE/blob/09194c709fa29219d11312f5776f56492646409a/data/coco_train_dataset.py#L161) shows how the same transformation is ensured. We basically keep random geometric transforms for each data point every iteration and retrieve the same set of transformation with the data index.

**Comment by JudgeLJX** [comment]
Thanks for your explanation!
