### ISSUE TITLE
CE Weights After Labelling

### ISSUE THREAD

**Issue by gorkaydemir** [janghyuncho/PiCIE#28]
Hello, thanks for your work and making it public.
In the `compute_labels` function, after centroid assignments are found, assignment counts are accumulated to get the CE weights due to possible imbalance. However, classes are weighted directly proportional to assignment counts but not inversely proportional. I feel the weights should be inversely related to the pixel counts if the aim is solving the imbalance. Are there any reasons to make it directly proportional?

**Comment by janghyuncho** [comment]
Hi! Sorry for the very late response. We have
