### ISSUE TITLE
Error reported when running train_picie.py file，What is the reason？

### ISSUE THREAD

**Issue by Chriost** [janghyuncho/PiCIE#33]
File "/home/workshop/PiCIE/data/coco_eval_dataset.py", line 108, in <lambda>
    fine_to_coarse_map       = np.vectorize(lambda x: fine_to_coarse_dict[x]) # not in-place.
KeyError: 183

**Comment by janghyuncho** [comment]
Hi, 

It seems like there is an issue with label transformation part during evaluation.
