### ISSUE TITLE
How do we get fine_to_coarse_dict.pickle  to train our data sets？

### ISSUE THREAD

**Issue by Chriost** [janghyuncho/PiCIE#34]
I tested the source code on the coco dataset， But now I want to train own data set，So how to get fine_to_coarse_dict.pickle ？

**Comment by smithalas** [comment]
It's very difficult in general to know how to apply PiCIE to your own datasets I'm finding

**Comment by Chriost** [comment]
I got it, Thank you!


蔡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "janghyuncho/PiCIE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 晚上9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [janghyuncho/PiCIE] How do we get fine_to_coarse_dict.pickle  to train our data sets？ (Issue #34)





 
Hi,
 
find_to_coarse_dict is used for COCO-27 evaluation only, following prior work (IIC).
 This is used to make the original COCO-Stuff classes coarse, since unsupervised learning on 100+ classes is too difficult.
 
In general, you need to have your own data loader for your custom data. Starting from here, modifying load_data and _label_transform is a good start. If your own custom data is already coarse and have well-defined label system (labels from 0 to K), you can comment this out.
 
Hope this helps.
