### ISSUE TITLE
The number of GPUs?

### ISSUE THREAD

**Issue by lzyhha** [janghyuncho/PiCIE#8]
Hello, thanks for your great work. And now, I am trying to train the model in my device. Can you tell me how many GPUs you used to train the model?

**Comment by janghyuncho** [comment]
Hi lzyhha, 

Thank you for your interest in PiCIE! 

All models in our project was run with a single V100. 

Best, 

Jang Hyun

**Comment by lzyhha** [comment]
Is it a 32GB v100? or just 16GB?:blush:

**Comment by janghyuncho** [comment]
I have been using 32GB V100, but I think you can decrease the batch size during the training phase.

**Comment by lzyhha** [comment]
Ok, thanks for your reply. I think I can use two or more gpus.:blush:
