### ISSUE TITLE
Custom datasets

### ISSUE THREAD

**Issue by Chic-J** [janghyuncho/PiCIE#9]
thanks for this work.
anyway, i have my own dataset with .jpg for img and .png for label.
i wonder is there any way to use my own dataset?

**Comment by janghyuncho** [comment]
Hi Chic-J, 

Thank you for your interest in PiCIE. As long as you have your dataset folder formatted as [this](https://github.com/janghyuncho/PiCIE#preparing-dataset), your custom dataset should work. 

During training, you will not need your labels and training code should work as it is. 
During testing, you may want to modify label transformation function ([here](https://github.com/janghyuncho/PiCIE/blob/1d7b034f57e98670b0d6a244b2eea11fa0dde73e/data/coco_eval_dataset.py#L109)). I think commenting out line 118 to line 126 would work.

Best,
Jang Hyun

**Comment by Chic-J** [comment]
> Hi Chic-J,
> 
> Thank you for your interest in PiCIE. As long as you have your dataset folder formatted as [this](https://github.com/janghyuncho/PiCIE#preparing-dataset) (you do not need the json files), your custom dataset should work without any problem.
> 
> During training, you do not need your labels and the training code should work as it is.
> During testing, you may want to modify the label transformation function ([here](https://github.com/janghyuncho/PiCIE/blob/1d7b034f57e98670b0d6a244b2eea11fa0dde73e/data/coco_eval_dataset.py#L109)). I think commenting out line 118 to line 126 would work.
> 
> Best,
> Jang Hyun

thanks. And yes, I don't have any fine_to_coarse_dict...so i just ignore the code related to it, does it matter?

**Comment by janghyuncho** [comment]
Yes. fine_to_coarse_dict is used to map the original COCO-Stuff categories to more coarse set of categories.

**Comment by Chic-J** [comment]
> Yes. fine_to_coarse_dict is used to map the original COCO-Stuff categories to more coarse set of categories.

yes, I got it. Thanks.

**Comment by janghyuncho** [comment]
Glad I could help!

**Comment by tanveer6715** [comment]
Hi @Chic-J ,

Have you successfully trained PiCIE using custom dataset? I am trying to train with custom dataset but I dont have pkl file and lists. I have only images and annotations.

**Comment by Chic-J** [comment]
> Hi @Chic-J ,
> 
> Have you successfully trained PiCIE using custom dataset? I am trying to train with custom dataset but I dont have pkl file and lists. I have only images and annotations.

Hi. I gave up due to the same reason. good luck to you.
